# config/packages/sonata_admin.yaml
sonata_admin:
  title: 'TusKamisetas'
  title_logo: 'icon.png' # Asegúrate de que este fichero está en tu carpeta public/
  options:
    # Esta línea establece 'edit' como la acción por defecto
    # para los enlaces de la vista de lista en todos los Admin.
    default_admin_route: edit
  dashboard:
    groups:
      # NOTA: Los IDs de grupo ahora son simples claves de texto.
      # Los 'items' ahora usan el nombre completo de la clase del Admin.
      Usuarios:
        label: Usuarios
        label_catalogue: SonataAdminBundle
        icon: '<i class="fas fa-users"></i>'
        roles: [ 'ROLE_SUPER_ADMIN' ]
        items:
          - App\Admin\ContactoAdmin # antes sonata.admin.clientes
          - App\Admin\GroupAdmin      # antes sonata.user.admin.group
          - App\Admin\DescuentoAdmin  # antes sonata.admin.descuentos

      Configuracion:
        label: Configuración
        label_catalogue: SonataAdminBundle
        icon: '<i class="fas fa-cog"></i>'
        roles: [ 'ROLE_SUPER_ADMIN' ]
        items:
          - App\Admin\EmpresaAdmin
          - App\Admin\BannerHomeAdmin
          - sonata.media.admin.media # antes sonata.media.admin.media

      Clasificacion:
        label: Clasificación
        label_catalogue: SonataAdminBundle
        icon: '<i class="fas fa-th"></i>'
        roles: [ 'ROLE_SUPER_ADMIN' ]
        items:
          # Estos son los admins que vienen con el ClassificationBundle
          - sonata.classification.admin.category
          - sonata.classification.admin.collection
          - sonata.classification.admin.tag

      Productos:
        label: Productos
        label_catalogue: SonataAdminBundle
        icon: '<i class="fas fa-tag"></i>'
        roles: [ 'ROLE_SUPER_ADMIN' ]
        items:
          - App\Admin\ProveedorAdmin
          - App\Admin\FabricanteAdmin
          - App\Admin\ModeloAdmin
          - App\Admin\FamiliaAdmin
          - App\Admin\ModeloAtributoAdmin
          - App\Admin\ColorAdmin
          - App\Admin\InventarioAdmin

      Tienda:
        label: Tienda
        label_catalogue: SonataAdminBundle
        icon: '<i class="fas fa-shopping-cart"></i>'
        roles: [ 'ROLE_SUPER_ADMIN' ]
        items:
          - App\Admin\PedidoAdmin
          - App\Admin\ZonaEnvioAdmin # antes sonata.admin.gastos.envio
          - App\Admin\PersonalizacionAdmin
          - App\Admin\TarifaAdmin
          - App\Admin\OfertaAdmin
          - App\Admin\FacturaAdmin
          - App\Admin\FacturaRectificativaAdmin

      Blog:
        label: Blog
        label_catalogue: SonataAdminBundle
        icon: '<i class="fas fa-comments"></i>'
        items:
          - App\Admin\PublicacionAdmin # antes sonata.admin.publicaciones

    # AHORA (Correcto)
    blocks:
      - { type: App\Block\ResumenFinancieroBlockService, position: top, class: 'col-lg-12' }


      - { type: sonata.admin.block.stats, position: top, class: 'col-lg-3 col-xs-6', settings: { code: App\Admin\PedidoAdmin, icon: 'fas fa-shopping-cart', text: 'Pedidos Nuevos Sin Revisar', color: 'bg-aqua', filters: { estado: { value: 1 } } } }
      - { type: sonata.admin.block.stats, position: top, class: 'col-lg-3 col-xs-6', settings: { code: App\Admin\PedidoAdmin, icon: 'fas fa-money-bill-alt', text: 'Revisados Sin Pagar', color: 'bg-red', filters: { estado: { value: 3 }, cantidadPagada: { type: '<=', value: 0 } } } }
      - { type: sonata.admin.block.stats, position: top, class: 'col-lg-3 col-xs-6', settings: { code: App\Admin\PedidoAdmin, icon: 'fas fa-handshake', text: 'Pedir a Proveedor', color: 'bg-green', filters: { pedidoAProveedor: { value: 0 } } } }
      - { type: sonata.admin.block.stats, position: top, class: 'col-lg-3 col-xs-6', settings: { code: sonata.user.admin.user, icon: 'fas fa-user', text: 'Total de Usuarios', color: 'bg-yellow', filters: { enabled: { value: 1 } } } }
      # ... etc

      # Bloques personalizados (necesitan migración de su código PHP)
      - { type: App\Block\PedidosPendientesBlockService, position: top, class: 'col-lg-12 col-xs-12' }
      - { type: App\Block\PedidosRecientesBlockService, position: top, class: 'col-lg-6 col-xs-12' }
      - { type: App\Block\ClientesRecientesBlockService, position: top, class: 'col-lg-6 col-xs-12' }

      - { type: App\Block\PedidosComparativaBlockService, position: top, class: 'col-lg-12' }

  templates:
    layout: 'admin/layout.html.twig' # Asegúrate de que esta plantilla existe en /templates/admin/
    # ... (el resto de tus plantillas)

  assets:
#    extra_javascripts:
#      - bundles/fosckeditor/ckeditor.js
    extra_stylesheets:
      - bundles/sonatatranslation/css/sonata-translation.css